# Generated by Django 5.1.6 on 2025-05-01 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('team', models.CharField(max_length=100)),
                ('is_public', models.IntegerField(choices=[(0, 'none'), (1, 'read_only')], default='0')),
                ('authenticated_permission', models.IntegerField(choices=[(0, 'none'), (1, 'read_only'), (2, 'read_and_write')], default='1')),
                ('group_permission', models.IntegerField(choices=[(0, 'none'), (1, 'read_only'), (2, 'read_and_write')], default='1')),
                ('author_permission', models.IntegerField(choices=[(2, 'read_and_write')], default=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
