# Generated by Django 5.1.6 on 2025-03-12 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='group_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='authenticated_permission',
            field=models.CharField(choices=[(0, 'none'), (1, 'read_only'), (2, 'read_and_write')], default='1', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='group_permission',
            field=models.CharField(choices=[(0, 'none'), (1, 'read_only'), (2, 'read_and_write')], default='1', max_length=20),
        ),
    ]
