# Generated by Django 5.1.6 on 2025-03-12 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_post_authenticated_permission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author_permission',
            field=models.IntegerField(choices=[(2, 'read_and_write')], default=2),
        ),
        migrations.AlterField(
            model_name='post',
            name='is_public',
            field=models.IntegerField(choices=[(0, 'none'), (1, 'read_only')], default='0'),
        ),
    ]
