# Generated by Django 5.1.6 on 2025-05-01 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='group_name',
            new_name='team',
        ),
    ]
