# Generated by Django 5.1.6 on 2025-03-12 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='group',
        ),
        migrations.AddField(
            model_name='user',
            name='group_name',
            field=models.CharField(default='default_group', max_length=100),
        ),
    ]
