# Generated by Django 5.1.6 on 2025-03-12 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_group_user_group_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='group_name',
            field=models.CharField(max_length=100),
        ),
    ]
