# Generated by Django 5.1.6 on 2025-03-05 21:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_blogger_group_blogger_delete_blogger'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blogger_Group',
            new_name='User_Group',
        ),
    ]
